### ISSUE TITLE
[BUG] wrong cooldown in enter-cooldown-message 

### ISSUE THREAD

**Issue by MrKrakenied** [XZot1K/SimplePortals#26]
Cooldown works as intended but {time} always shows 0.
```
keep-teleport-head-axis: false
bypass-portal-permissions: true
vehicle-teleportation: false
block-creative-portal-entrance: true
creature-spawning-blacklist:
  - "PUFFERFISH"
  - "TROPICAL_FISH"
  - "DOLPHIN"
titles:
  fade-in: 0
  fade-out: 0
  display-time: 5
use-portal-cooldown: true
join-protection: false
join-protection-cooldown: 5
portal-cooldown-duration: 10
throw-velocity: 1.5
command-tick-delay: 5
teleport-sound: "ENTITY_GHAST_SHOOT"
teleport-visual-effect: "CLOUD"
selection-visual-effect: "REDSTONE"
selection-visual-duration: 10
region-visual-effect: "REDSTONE"
region-visual-duration: 20
```
