### ISSUE TITLE
[BUG]Could not pass event AsyncPlayerPreLoginEvent to SimplePortals v1.7.5 / Cannot invoke "java.sql.Connection.prepareStatement"

### ISSUE THREAD

**Issue by waseric** [XZot1K/SimplePortals#46]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
On a bungee network running latest waterfall and 1.20.4 paper:
1. Upgrade SimplePortals v1.7.4 to v1.7.5.
  1. Server starts without exceptions.  
  2. console notes updates (or none, as appropriate) to config file.
  3. No local sqlite db created in response to (default) empty mysql.host: config element.
4. Using 1.20.1 or 1.20.4 client, Join server through proxy.
5. Observe exception in console:

```
[12:21:10 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to SimplePortals v1.7.5
lobby        | java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(java.lang.String)" because the return value of "xzot1k.plugins.sp.SimplePortals.getDatabaseConnection()" is null
lobby        |  at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
lobby        |  at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
lobby        | Caused by: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(java.lang.String)" because the return value of "xzot1k.plugins.sp.SimplePortals.getDatabaseConnection()" is null
lobby        |  at xzot1k.plugins.sp.core.Listeners.lambda$onPreJoin$0(Listeners.java:122) ~[SimplePortals.jar:?]
lobby        |  ... 7 more
```

content automatically added to SimplePortals/config.yml  (no manual changes made yet)
```
mysql:
  # Ensure this is the name used within your proxy's configuration
  server-name: lobby
  # The "use-ssl" feature enables SSL connection support
  use-ssl: false
  # Name of the database
  database: SimplePortals
  # Name of the table used for transfer data
  transfer-table: transfer
  # The "host" option can be left blank to determine whether mysql is used or not
  # If disabled, SQLite will be used locally instead
  host: ''
  port: 3306
  username: root
  password: ''
portal-to-portal-protection: true
```

**Expected behavior**
No exceptions on player join.  Per comments in new elements of config.yml:
```
  # The "host" option can be left blank to determine whether mysql is used or not
  # If disabled, SQLite will be used locally instead
  host: ''
```

**Server Information (Please fill in the information below):**
 - Version: Paper 1.20.4 (build 405)
 - Plugins: [several -- will provide if needed; issue seems self-contained]

**Additional context**
I will be configuring DB, so this is not a critical issue for me.  Raising visibility only.
